version: '3.8'

services:
  # Servicio para la base de datos MySQL
  db:
    image: mysql:5.7
    container_name: portfolio_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '8081:80'
    networks:
      - wordpress_network

  # Servicio para WordPress
  wordpress:
    image: wordpress:latest
    container_name: portfolio_wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    ports:
      - '8080:80'
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - wordpress_network

  # Servicio para Apache
  apache:
    image: httpd:latest
    container_name: portfolio_apache
    restart: always
    ports:
      - '8082:80'
    volumes:
      - ./apache_data:/usr/local/apache2/htdocs
    networks:
      - wordpress_network

volumes:
  db_data:
  wordpress_data:
  apache_data:

networks:
  wordpress_network:
